//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GearChart.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GearChart.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Chart.
        /// </summary>
        internal static string AddChart {
            get {
                return ResourceManager.GetString("AddChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. gear ratio.
        /// </summary>
        internal static string AverageRatio {
            get {
                return ResourceManager.GetString("AverageRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cassette.
        /// </summary>
        internal static string Cassette {
            get {
                return ResourceManager.GetString("Cassette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain Ring.
        /// </summary>
        internal static string ChainRing {
            get {
                return ResourceManager.GetString("ChainRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Details.
        /// </summary>
        internal static string ChartDetails {
            get {
                return ResourceManager.GetString("ChartDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coasting.
        /// </summary>
        internal static string Coasting {
            get {
                return ResourceManager.GetString("Coasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation Analysis.
        /// </summary>
        internal static string ElevationAnalysis {
            get {
                return ResourceManager.GetString("ElevationAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Grade Effect CSV.
        /// </summary>
        internal static string ExportGradeEffectCSV {
            get {
                return ResourceManager.GetString("ExportGradeEffectCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in Google Maps.
        /// </summary>
        internal static string ExportTitle {
            get {
                return ResourceManager.GetString("ExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear ratio (Raw).
        /// </summary>
        internal static string GearRatioRawText {
            get {
                return ResourceManager.GetString("GearRatioRawText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear ratio.
        /// </summary>
        internal static string GearRatioText {
            get {
                return ResourceManager.GetString("GearRatioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear Selection.
        /// </summary>
        internal static string GearSelection {
            get {
                return ResourceManager.GetString("GearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gears.
        /// </summary>
        internal static string GearsText {
            get {
                return ResourceManager.GetString("GearsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear vs. Avg..
        /// </summary>
        internal static string GearVsAvg {
            get {
                return ResourceManager.GetString("GearVsAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hill Finder.
        /// </summary>
        internal static string HillFinder {
            get {
                return ResourceManager.GetString("HillFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. gear ratio.
        /// </summary>
        internal static string MaxRatio {
            get {
                return ResourceManager.GetString("MaxRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. gear ratio.
        /// </summary>
        internal static string MinRatio {
            get {
                return ResourceManager.GetString("MinRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most used gear.
        /// </summary>
        internal static string MostUsedGear {
            get {
                return ResourceManager.GetString("MostUsedGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /rev..
        /// </summary>
        internal static string PerRevText {
            get {
                return ResourceManager.GetString("PerRevText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RouteExtras.
        /// </summary>
        internal static string RouteExtrasText {
            get {
                return ResourceManager.GetString("RouteExtrasText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Charts.
        /// </summary>
        internal static string SelectedCharts {
            get {
                return ResourceManager.GetString("SelectedCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear setup :.
        /// </summary>
        internal static string SelectEquipmentLabelText {
            get {
                return ResourceManager.GetString("SelectEquipmentLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select gear setup.
        /// </summary>
        internal static string SelectGearsEquipmentDialogText {
            get {
                return ResourceManager.GetString("SelectGearsEquipmentDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Time Track.
        /// </summary>
        internal static string UpdateTimeTrack {
            get {
                return ResourceManager.GetString("UpdateTimeTrack", resourceCulture);
            }
        }
    }
}
